import { mount } from 'svelte'
// Fonts first: the @font-face sheet is generated by scripts/fetch-fonts.cjs and bundled into the
// same stylesheet as the app, so the faces are declared without a second network request.
import './fonts.css'
import './app.css'
import App from './App.svelte'

const app = mount(App, {
  target: document.getElementById('app'),
})

export default app
